class EducationSkillsData {
  static const List<String> educationOptions = [
    'High School',
    'Diploma in Computer Science',
    'Diploma in Information Technology',
    'Diploma in Software Engineering',
    'Diploma in Network Engineering',
    'Diploma in Cyber Security',
    'Diploma in Data Analytics',
    'Diploma in Web Development',
    'Diploma in Mobile App Development',
    'Diploma in Game Development',
    'Diploma in Database Management',
    'Diploma in Cloud Computing',
    'Diploma in System Administration',
    'Bachelor of Computer Science',
    'Bachelor of Information Technology',
    'Bachelor of Software Engineering',
    'Bachelor of Data Science',
    'Bachelor of Artificial Intelligence',
    'Bachelor of Cyber Security',
    'Bachelor of Information Systems',
    'Bachelor of Computer Engineering',
    'Bachelor of Network Engineering',
    'Bachelor of Game Development',
    'Bachelor of Cloud Computing',
    'Bachelor of Machine Learning',
    'Bachelor of Computer Networks',
    'Bachelor of Database Systems',
    'Bachelor of Web Technologies',
    'Bachelor of Mobile Computing',
    'Master of Computer Science',
    'Master of Information Technology',
    'Master of Software Engineering',
    'Master of Data Science',
    'Master of Artificial Intelligence',
    'Master of Cyber Security',
    'Master of Information Systems',
    'Master of Cloud Computing',
    'Master of Machine Learning',
    'Master of Computer Networks',
    'Master of Data Analytics',
    'Master of Blockchain Technology',
    'PhD in Computer Science',
    'PhD in Information Technology',
    'PhD in Software Engineering',
    'PhD in Data Science',
    'PhD in Artificial Intelligence',
    'PhD in Cyber Security',
    'PhD in Machine Learning',
    'PhD in Computer Networks',
    'PhD in Information Systems',
    'PhD in Cloud Computing',
    'PhD in Blockchain Technology',
    'PhD in Data Analytics',
    'Others'
  ];

  static const List<String> skillsOptions = [
    'Python',
    'Java',
    'JavaScript',
    'C++',
    'C#',
    'C',
    'PHP',
    'Ruby',
    'Swift',
    'Kotlin',
    'Go',
    'Rust',
    'TypeScript',
    'Dart',
    'R',
    'Scala',
    'Perl',
    'HTML/CSS',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'Laravel',
    'Spring Boot',
    'ASP.NET',
    'Ruby on Rails',
    'FastAPI',
    'Android Development',
    'iOS Development',
    'Flutter',
    'React Native',
    'Xamarin',
    'Ionic',
    'SQL',
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'Oracle Database',
    'Microsoft SQL Server',
    'SQLite',
    'Cassandra',
    'Firebase',
    'Data Science',
    'Machine Learning',
    'Deep Learning',
    'Artificial Intelligence',
    'Natural Language Processing',
    'Computer Vision',
    'Neural Networks',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Data Analysis',
    'Data Visualization',
    'Big Data',
    'Apache Spark',
    'Hadoop',
    'Cloud Computing',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'DevOps',
    'Docker',
    'Kubernetes',
    'CI/CD',
    'Jenkins',
    'GitLab CI',
    'Terraform',
    'Ansible',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Cyber Security',
    'Network Security',
    'Penetration Testing',
    'Ethical Hacking',
    'Cryptography',
    'Security Analysis',
    'Vulnerability Assessment',
    'Computer Networks',
    'Network Administration',
    'TCP/IP',
    'DNS',
    'VPN',
    'Firewall',
    'Load Balancing',
    'Software Development',
    'Object-Oriented Programming',
    'Functional Programming',
    'Design Patterns',
    'System Design',
    'Microservices',
    'RESTful API',
    'GraphQL',
    'API Development',
    'Testing',
    'Unit Testing',
    'Integration Testing',
    'Test Automation',
    'Agile',
    'Scrum',
    'Game Development',
    'Unity',
    'Unreal Engine',
    '3D Programming',
    'Blockchain',
    'Smart Contracts',
    'Ethereum',
    'Solidity',
    'Web3',
    'Linux',
    'Shell Scripting',
    'Bash',
    'PowerShell',
    'System Administration',
    'Server Management',
    'IoT',
    'Embedded Systems',
    'Algorithms',
    'Data Structures',
    'Problem Solving',
    'Others'
  ];
}